[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -I ../include
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_ESP32C3_SUPERMINI
    -DSTATUS_LED_PIN=8

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.4
    links2004/WebSockets @ ^2.7.3

[env:lolin_c3_mini]
extends = env:esp32-c3-supermini
